title: Derek & Sarah Kershner's Travels
description: Follow the travel adventures of Derek & Sarah Kershner
show_downloads: false
google_analytics: UA-10014066-3

github:
  owner-name: Derek Kershner
  is_project_page: false

paginate: 5

theme: jekyll-theme-cayman
