---
label: Default
hide_body: false
is_partial: false
fields:
- type: text
  name: author
  label: Author
  description: Who is writing this?
  config:
    required: true
  default: Sarah Kershner
pages:
- _posts/test.md
